server.port=8083
spring.application.name=jira
spring.datasource.url=jdbc:postgresql://localhost:5432/jira_tickets_db
spring.datasource.username=jira_user
spring.datasource.password=secret_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Every consumer needs a Group ID to track its reading progress (offset)
spring.kafka.consumer.group-id=ticket-service-group
spring.kafka.consumer.auto-offset-reset=earliest